# Customer Churn Prediction using Explainable AI

## Notebook 05: Model Training

## Project Overview

In the previous notebooks, the customer churn dataset was understood, cleaned, explored, and transformed through feature engineering.

The final feature-engineered dataset is now ready for machine learning.

In this notebook, multiple classification algorithms are trained to predict whether a customer is likely to churn.

The following machine learning models are trained:

- Logistic Regression
- Decision Tree Classifier
- Random Forest Classifier
- XGBoost Classifier

A preprocessing pipeline is used to handle both numerical and categorical features appropriately before model training.

The trained models will be saved for the next phase, where their performance will be evaluated and compared.

## Objectives

The objectives of this notebook are to:

- Load the final feature-engineered dataset.
- Separate the input features from the target variable.
- Identify numerical and categorical features.
- Split the dataset into training and testing sets.
- Apply appropriate preprocessing to numerical and categorical features.
- Train multiple classification models.
- Generate predictions and churn probabilities from each model.
- Save the trained models for the evaluation and deployment phases.

## Importing Required Libraries:



In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer                        # performs  different transformations on different columns
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline                                # pipeline -> sequence of steps
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier                                    # Gradient boosting classifier


import warnings
warnings.filterwarnings("ignore")

## Load Final Dataset

The final feature-engineered dataset created in Notebook 04 is loaded.

No additional data cleaning or feature removal is performed in this notebook because those tasks were completed in the previous phases.

In [ ]:
file_path = "/content/Featured_telco_churn.csv"
df = pd.read_csv(file_path,encoding = 'ISO-8859-1')
#print(df.head())
print(df.shape)
#print(df.info())
#print(df.describe)
print(df.columns)

(7043, 26)
Index(['Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Tenure Months',
       'Phone Service', 'Multiple Lines', 'Internet Service',
       'Online Security', 'Online Backup', 'Device Protection', 'Tech Support',
       'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing',
       'Payment Method', 'Monthly Charges', 'Total Charges', 'Churn Value',
       'CLTV', 'Total Aditional Services', 'Total Streaming Services',
       'Total Security Services', 'Tenure Group', 'Has Multiple Services'],
      dtype='object')


In [ ]:
print(df.isnull().sum().sum())
print(df.duplicated().sum())

0
0


## Define Target Variable

The target variable is `Churn Value`.

It represents the customer's churn status:

- 0 → Customer did not churn
- 1 → Customer churned

Therefore, this is a binary classification problem.

In [ ]:
y  = df["Churn Value"]
#print(y.value_counts())
print(y.value_counts(normalize = "index")*100)

Churn Value
0    73.463013
1    26.536987
Name: proportion, dtype: float64


## Define Feature Matrix

All columns except the target variable are used as input features.

The feature matrix `X` contains the information that the machine learning models will use to predict customer churn.

In [ ]:
x = df.drop(["Churn Value"],axis = 1)
print(x.shape)

(7043, 25)


## Identify Feature Types

The feature matrix contains both numerical and categorical variables.

Numerical variables can be directly processed after scaling, while categorical variables need to be converted into numerical form.

Therefore:

- Numerical features → StandardScaler
- Categorical features → OneHotEncoder

In [ ]:
numeric_features = x.select_dtypes(include=["int64", "float64"]).columns.tolist()

categorical_features = x.select_dtypes(include=["object"]).columns.tolist()

print("Numerical Features:")
print(numeric_features)

print("\nCategorical Features:")
print(categorical_features)

Numerical Features:
['Tenure Months', 'Monthly Charges', 'Total Charges', 'CLTV', 'Total Aditional Services', 'Total Streaming Services', 'Total Security Services', 'Has Multiple Services']

Categorical Features:
['Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Phone Service', 'Multiple Lines', 'Internet Service', 'Online Security', 'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method', 'Tenure Group']


## Train-Test Split

The dataset is divided into training and testing sets.

- 80% of the data will be used for training.
- 20% will be used for testing.

Stratified splitting is used so that the proportion of churned and non-churned customers remains approximately consistent in both datasets.

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.20,random_state= 42,stratify = y)
#check:
print(x_train.shape,x_test.shape)
print(y_train.shape,y_test.shape)


(5634, 25) (1409, 25)
(5634,) (1409,)


## Preprocessing Pipeline

Machine learning algorithms require numerical input.

Numerical features are standardized using StandardScaler.

Categorical features are converted into numerical representations using OneHotEncoder.

A ColumnTransformer is used to apply the appropriate transformation to each feature type.

The preprocessing steps are included inside the machine learning pipeline so that they are fitted only on the training data.

In [ ]:
preprocessor = ColumnTransformer(
    transformers = [
        ("numeric",StandardScaler(),numeric_features),
        ("categorical",OneHotEncoder(handle_unknown = "ignore"),categorical_features)
    ]
)

### ColumnTransformer — Concept

`ColumnTransformer` is used when **different columns need different preprocessing**.

Example:
- Numerical columns → `StandardScaler`
- Categorical columns → `OneHotEncoder`

### Syntax

```python
ColumnTransformer([
    ("name", transformer, columns)
])

## Model 1: Logistic Regression

Logistic Regression is used as the baseline classification model.

It is a simple and interpretable algorithm for binary classification and provides a useful benchmark for comparing more advanced models.

In [ ]:
logistic_model = Pipeline(
    steps = [
        ("Preprocessor",preprocessor),
        ("model",LogisticRegression(max_iter = 1000))                  # max_iter mean maximum iterations
    ]
)

In [ ]:
logistic_model.fit(x_train,y_train)

Pipeline(steps=[('Preprocessor',
                 ColumnTransformer(transformers=[('numeric', StandardScaler(),
                                                  ['Tenure Months',
                                                   'Monthly Charges',
                                                   'Total Charges', 'CLTV',
                                                   'Total Aditional Services',
                                                   'Total Streaming Services',
                                                   'Total Security Services',
                                                   'Has Multiple Services']),
                                                 ('categorical',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Gender', 'Senior Citizen',
                                                   'Partner', 'Dependents',
                                                   'Phone Service',
                                                   'Multiple Lines',
                                                   'Internet Service',
                                                   'Online Security',
                                                   'Online Backup',
                                                   'Device Protection',
                                                   'Tech Support',
                                                   'Streaming TV',
                                                   'Streaming Movies',
                                                   'Contract',
                                                   'Paperless Billing',
                                                   'Payment Method',
                                                   'Tenure Group'])])),
                ('model', LogisticRegression(max_iter=1000))])

In [ ]:
lr_pred = logistic_model.predict(x_test)
lr_proba = logistic_model.predict_proba(x_test)[:,1]
print(lr_pred[:10])
#print(lr_proba[:10])

[0 1 0 0 0 1 0 0 0 0]


## Model 2: Decision Tree Classifier

Decision Tree Classifier learns a sequence of decision rules from the data.

It can capture non-linear relationships between customer characteristics and churn.

In [ ]:
decision_classifier = Pipeline(
    steps = [
        ("Preprocessor",preprocessor),
        ("model",DecisionTreeClassifier(max_depth = 5,random_state = 42))           # max_depth mean total number of levels for tree
    ]
)

In [ ]:
decision_classifier.fit(x_train,y_train)

Pipeline(steps=[('Preprocessor',
                 ColumnTransformer(transformers=[('numeric', StandardScaler(),
                                                  ['Tenure Months',
                                                   'Monthly Charges',
                                                   'Total Charges', 'CLTV',
                                                   'Total Aditional Services',
                                                   'Total Streaming Services',
                                                   'Total Security Services',
                                                   'Has Multiple Services']),
                                                 ('categorical',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Gender', 'Senior Citizen',
                                                   'Partner', 'Dependents',
                                                   'Phone Service',
                                                   'Multiple Lines',
                                                   'Internet Service',
                                                   'Online Security',
                                                   'Online Backup',
                                                   'Device Protection',
                                                   'Tech Support',
                                                   'Streaming TV',
                                                   'Streaming Movies',
                                                   'Contract',
                                                   'Paperless Billing',
                                                   'Payment Method',
                                                   'Tenure Group'])])),
                ('model',
                 DecisionTreeClassifier(max_depth=5, random_state=42))])

In [ ]:
dt_pred = decision_classifier.predict(x_test)
print(dt_pred[:10])

[0 1 0 1 0 0 0 0 0 0]


In [ ]:
dt_proba = decision_classifier.predict_proba(x_test)[:,1]
print(dt_proba[:10])

[0.06086957 0.68380952 0.02991945 0.54347826 0.02991945 0.39325843
 0.39325843 0.15141956 0.         0.38461538]


## Model 3: Random Forest Classifier

Random Forest is an ensemble learning algorithm that combines multiple decision trees.

It can capture complex relationships in structured customer data and is generally more robust than a single decision tree.

In [ ]:
random_forest = Pipeline(
    steps = [
        ("Preprocessor",preprocessor),
        ("model",RandomForestClassifier(n_estimators = 100,random_state = 42))        # n_estimators mean totol number of trees
    ]
)

In [ ]:
random_forest.fit(x_train,y_train)                            # training of model

Pipeline(steps=[('Preprocessor',
                 ColumnTransformer(transformers=[('numeric', StandardScaler(),
                                                  ['Tenure Months',
                                                   'Monthly Charges',
                                                   'Total Charges', 'CLTV',
                                                   'Total Aditional Services',
                                                   'Total Streaming Services',
                                                   'Total Security Services',
                                                   'Has Multiple Services']),
                                                 ('categorical',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Gender', 'Senior Citizen',
                                                   'Partner', 'Dependents',
                                                   'Phone Service',
                                                   'Multiple Lines',
                                                   'Internet Service',
                                                   'Online Security',
                                                   'Online Backup',
                                                   'Device Protection',
                                                   'Tech Support',
                                                   'Streaming TV',
                                                   'Streaming Movies',
                                                   'Contract',
                                                   'Paperless Billing',
                                                   'Payment Method',
                                                   'Tenure Group'])])),
                ('model', RandomForestClassifier(random_state=42))])

In [ ]:
rf_pred = random_forest.predict(x_test)                        # making predictions
print(rf_pred[:10])

[0 1 0 0 0 0 0 0 0 0]


In [ ]:
rf_proba = random_forest.predict_proba(x_test)[:,1]                # calculating probability
print(rf_proba[:10])

[0.05 0.75 0.09 0.35 0.04 0.34 0.33 0.14 0.   0.32]


## Model 4: XGBoost Classifier

XGBoost is an advanced gradient boosting algorithm.

It builds multiple decision trees sequentially, with each new tree attempting to improve the errors made by previous trees.

It is included to determine whether an advanced boosting approach can provide better predictive performance for customer churn.

- XGBoost doesn't work exactly like Random Forest. Random Forest builds many trees independently and combines their votes, while XGBoost builds trees sequentially, with each new tree trying to improve the previous model.

`eval_metric="logloss" `  This tells XGBoost:

Use Log Loss to evaluate the model's predictions during training.

In [ ]:
xgb_classifier = Pipeline(
    steps= [
        ("preprocessor",preprocessor),
        ("model",XGBClassifier(
            n_estimators = 200,
            max_depth= 4,
            learning_rate= 0.05,
            random_state = 42,
            eval_metric = "logloss"

        ))
    ]
)

In [ ]:
xgb_classifier.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numeric', StandardScaler(),
                                                  ['Tenure Months',
                                                   'Monthly Charges',
                                                   'Total Charges', 'CLTV',
                                                   'Total Aditional Services',
                                                   'Total Streaming Services',
                                                   'Total Security Services',
                                                   'Has Multiple Services']),
                                                 ('categorical',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Gender', 'Senior Citizen',
                                                   'Partner', 'Dependents',
                                                   'P...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=4, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=200, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [ ]:
xgb_pred = xgb_classifier.predict(x_test)
print(xgb_pred[:10])

[0 1 0 0 0 1 0 0 0 0]


In [ ]:
xgb_proba = xgb_classifier.predict_proba(x_test)[:,1]
print(xgb_proba[:10])

[0.0404616  0.7906848  0.17282204 0.4787223  0.02804929 0.5874926
 0.4342194  0.09625477 0.00274186 0.3562002 ]


### Saving Trained Models

`joblib` is a python library and used to **save trained models** so they can be reused later (streamlit) without training them again.

`.pkl` is  basically saved Python object/model file.


In [ ]:
import joblib

models = {
    "Logistic Regression": logistic_model,
    "Decision Tree": decision_classifier,
    "Random Forest": random_forest,
    "XGBoost": xgb_classifier
}

joblib.dump(models, "churn_models.pkl")

['churn_models.pkl']

In [ ]:
Evaluation_data = {
    "y_test":y_test,
    "x_test":x_test,
    "Predictions":{
        "Logistic Regression": lr_pred,
        "Decision Tree": dt_pred,
        "Random Forest": rf_pred,
        "XGBoost": xgb_pred
    },
    "Probabilities":{
        "Logistic Regression": lr_proba,
        "Decision Tree": dt_proba,
        "Random Forest": rf_proba,
        "XGBoost": xgb_proba
    }
}
joblib.dump(Evaluation_data,"Evaluation_data.pkl")

['Evaluation_data.pkl']

## Conclusion

In this notebook, four machine learning classification models were trained to predict customer churn:

- Logistic Regression
- Decision Tree Classifier
- Random Forest Classifier
- XGBoost Classifier

A preprocessing pipeline was integrated with each model so that numerical and categorical features are transformed automatically during training and prediction.

The trained models have been saved for use in the next phase of the project.

In Notebook 06, these models will be evaluated and compared using appropriate classification metrics and visualizations. The best-performing model will then be selected for detailed evaluation and further explainability analysis.